// kanto-part1.js — pokemon entries for all 151
// To be spliced into personality-data.js by build-kanto.js
const KANTO_POKEMON = {
  bulbasaur:   { id:1,   typeId:12, name:'Bulbasaur',   type:'Grass',    color:'#4CD137',
                 traits:['Patient','Nurturing','Reliable','Steady'],
                 signatureMove:'Vine Whip', idealPartner:'Squirtle',
                 desc:"Patient, nurturing, and perpetually underrated, you're the person who actually holds everything together. You don't need the spotlight because your results speak louder than any announcement." },
  ivysaur:     { id:2,   typeId:12, name:'Ivysaur',     type:'Grass',    color:'#55efc4',
                 traits:['Dedicated','Steady','Growing','Determined'],
                 signatureMove:'Razor Leaf', idealPartner:'Wartortle',
                 desc:"You're mid-journey and you know it, which makes you more focused than most. Dedicated, steady, and genuinely building toward something real." },
  venusaur:    { id:3,   typeId:12, name:'Venusaur',    type:'Grass',    color:'#00b894',
                 traits:['Grounded','Wise','Protective','Powerful'],
                 signatureMove:'Solar Beam', idealPartner:'Blastoise',
                 desc:"Grounded, protective, and carrying a quiet authority earned through years of showing up. You've grown into your full strength and it shows in every room you enter." },
  charmander:  { id:4,   typeId:10, name:'Charmander',  type:'Fire',     color:'#e17055',
                 traits:['Passionate','Eager','Fierce','Loyal'],
                 signatureMove:'Ember', idealPartner:'Bulbasaur',
                 desc:"Burning with more intensity than your size suggests, you give everything to whatever you care about. Small, fierce, and loyal, you grow into something extraordinary." },
  charmeleon:  { id:5,   typeId:10, name:'Charmeleon',  type:'Fire',     color:'#d63031',
                 traits:['Rebellious','Competitive','Intense','Driven'],
                 signatureMove:'Flamethrower', idealPartner:'Wartortle',
                 desc:"You push back on anything that tries to limit you, and that defiance is actually your greatest asset. Competitive, intense, and deeply ambitious, you don't wait for permission." },
  charizard:   { id:6,   typeId:10, name:'Charizard',   type:'Fire',     color:'#E84118',
                 traits:['Ambitious','Fierce','Independent','Unstoppable'],
                 signatureMove:'Fire Blast', idealPartner:'Blastoise',
                 desc:"You've earned every bit of your reputation the hard way and you know it. Ambitious, fierce, and completely self-determined, you set the standard and other people try to meet it." },
  squirtle:    { id:7,   typeId:11, name:'Squirtle',    type:'Water',    color:'#0097e6',
                 traits:['Cool','Strategic','Dependable','Focused'],
                 signatureMove:'Water Gun', idealPartner:'Charmander',
                 desc:"Cool under pressure and always thinking two steps ahead, you almost always come out on top when it matters most. There's a calm confidence to you that people find genuinely magnetic." },
  wartortle:   { id:8,   typeId:11, name:'Wartortle',   type:'Water',    color:'#0652DD',
                 traits:['Composed','Mature','Confident','Reliable'],
                 signatureMove:'Bubble Beam', idealPartner:'Ivysaur',
                 desc:"You've outgrown the need to prove yourself constantly, and that maturity is your real strength. Composed, confident, and quietly formidable." },
  blastoise:   { id:9,   typeId:11, name:'Blastoise',   type:'Water',    color:'#1e3799',
                 traits:['Powerful','Steady','Respected','Immovable'],
                 signatureMove:'Hydro Pump', idealPartner:'Venusaur',
                 desc:"Steady, powerful, and completely impossible to move when you've decided your position. You've built something real and everyone around you knows it." },
  caterpie:    { id:10,  typeId:7,  name:'Caterpie',    type:'Bug',      color:'#78e08f',
                 traits:['Humble','Earnest','Patient','Hopeful'],
                 signatureMove:'String Shot', idealPartner:'Metapod',
                 desc:"Humble, earnest, and completely unashamed of starting at the very beginning. You trust the process because you already know where it leads." },
  metapod:     { id:11,  typeId:7,  name:'Metapod',     type:'Bug',      color:'#b8e994',
                 traits:['Patient','Enduring','Still','Resilient'],
                 signatureMove:'Harden', idealPartner:'Caterpie',
                 desc:"Internally, you're doing the most important work of your life right now, and nobody can see it. Patient, enduring, and completely undistracted by what others think." },
  butterfree:  { id:12,  typeId:7,  name:'Butterfree',  type:'Bug',      color:'#a29bfe',
                 traits:['Free','Expressive','Evolved','Beautiful'],
                 signatureMove:'Psychic', idealPartner:'Pidgeot',
                 desc:"You emerged as something completely different from where you started, and you wear that transformation openly. Free, expressive, and genuinely beautiful in motion." },
  weedle:      { id:13,  typeId:7,  name:'Weedle',      type:'Bug',      color:'#f9ca24',
                 traits:['Scrappy','Persistent','Underestimated','Sharp'],
                 signatureMove:'Poison Sting', idealPartner:'Beedrill',
                 desc:"Scrappy, persistent, and carrying a lot more sting than people expect at first glance. You don't need a grand introduction, your results make it." },
  kakuna:      { id:14,  typeId:7,  name:'Kakuna',      type:'Bug',      color:'#f6e58d',
                 traits:['Patient','Quiet','Transforming','Determined'],
                 signatureMove:'Harden', idealPartner:'Weedle',
                 desc:"You're in a critical phase of becoming and you know better than to rush it. Patient, quiet, and transforming on the inside while the world waits." },
  beedrill:    { id:15,  typeId:7,  name:'Beedrill',    type:'Bug',      color:'#fbc531',
                 traits:['Fierce','Protective','Loyal','Community-minded'],
                 signatureMove:'Twineedle', idealPartner:'Butterfree',
                 desc:"Fierce, protective, and completely devoted to the people and things you consider yours. Cross someone you care about and you'll see exactly what kind of threat you are." },
  pidgey:      { id:16,  typeId:1,  name:'Pidgey',      type:'Normal',   color:'#b2bec3',
                 traits:['Easygoing','Adaptable','Content','Low-key'],
                 signatureMove:'Gust', idealPartner:'Pidgeotto',
                 desc:"Easygoing, adaptable, and completely at peace with where you are right now. You don't force things, and somehow that means things tend to work out for you." },
  pidgeotto:   { id:17,  typeId:1,  name:'Pidgeotto',   type:'Normal',   color:'#a29bfe',
                 traits:['Steady','Hardworking','Reliable','Progressing'],
                 signatureMove:'Wing Attack', idealPartner:'Pidgey',
                 desc:"Steady, hardworking, and making real progress every single day even if no one's watching. You know where you're going and you're already on your way." },
  pidgeot:     { id:18,  typeId:1,  name:'Pidgeot',     type:'Normal',   color:'#fd79a8',
                 traits:['Graceful','Swift','Proud','Commanding'],
                 signatureMove:'Fly', idealPartner:'Raichu',
                 desc:"Graceful in motion and quietly proud of what you've become. You don't need to announce your speed, everyone can see it." },
  rattata:     { id:19,  typeId:1,  name:'Rattata',     type:'Normal',   color:'#9b59b6',
                 traits:['Tenacious','Resourceful','Scrappy','Fearless'],
                 signatureMove:'Super Fang', idealPartner:'Meowth',
                 desc:"Tenacious, resourceful, and completely unafraid of being the underdog. You survive on wit and persistence where others give up." },
  raticate:    { id:20,  typeId:1,  name:'Raticate',    type:'Normal',   color:'#8e44ad',
                 traits:['Efficient','No-nonsense','Focused','Sharp'],
                 signatureMove:'Hyper Fang', idealPartner:'Fearow',
                 desc:"No-nonsense, efficient, and exactly as sharp as you need to be. You don't waste time or energy on anything that doesn't move you forward." },
  spearow:     { id:21,  typeId:1,  name:'Spearow',     type:'Normal',   color:'#f0932b',
                 traits:['Blunt','Territorial','Direct','Honest'],
                 signatureMove:'Peck', idealPartner:'Fearow',
                 desc:"Blunt, direct, and completely uninterested in sugarcoating anything. People always know exactly where they stand with you, and most of them find that refreshing." },
  fearow:      { id:22,  typeId:1,  name:'Fearow',      type:'Normal',   color:'#e55039',
                 traits:['Assertive','Commanding','Proud','Territorial'],
                 signatureMove:'Drill Peck', idealPartner:'Raticate',
                 desc:"Commanding, assertive, and comfortable claiming the space you need. You've earned the right to be direct and you use it." },
  ekans:       { id:23,  typeId:4,  name:'Ekans',       type:'Poison',   color:'#a29bfe',
                 traits:['Patient','Cunning','Perceptive','Calm'],
                 signatureMove:'Wrap', idealPartner:'Arbok',
                 desc:"Patient, perceptive, and far more calculating than your casual manner suggests. You observe everything and act only when the moment is exactly right." },
  arbok:       { id:24,  typeId:4,  name:'Arbok',       type:'Poison',   color:'#6c5ce7',
                 traits:['Commanding','Intimidating','Wise','Instinctive'],
                 signatureMove:'Glare', idealPartner:'Raichu',
                 desc:"Commanding and instinctive, you project authority without needing to explain yourself. People sense it before you say a word." },
  pikachu:     { id:25,  typeId:13, name:'Pikachu',     type:'Electric', color:'#F7B731',
                 traits:['Energetic','Social','Brave','Loyal'],
                 signatureMove:'Thunderbolt', idealPartner:'Eevee',
                 desc:"You light up every room you walk into without even trying. Spirited, quick, and fiercely loyal, people gravitate toward your energy because it's completely real." },
  raichu:      { id:26,  typeId:13, name:'Raichu',      type:'Electric', color:'#e17055',
                 traits:['Confident','Experienced','Self-assured','Balanced'],
                 signatureMove:'Thunder', idealPartner:'Pidgeot',
                 desc:"You've grown into your power and you wear it comfortably. Confident, experienced, and self-assured in a way that can only come from actually doing the work." },
  sandshrew:   { id:27,  typeId:5,  name:'Sandshrew',   type:'Ground',   color:'#f9ca24',
                 traits:['Defensive','Practical','Grounded','Reliable'],
                 signatureMove:'Slash', idealPartner:'Sandslash',
                 desc:"Practical, grounded, and always prepared for what might come. You build security quietly and consistently, and people feel it when you're around." },
  sandslash:   { id:28,  typeId:5,  name:'Sandslash',   type:'Ground',   color:'#e2b96a',
                 traits:['Tough','Resilient','Reliable','Precise'],
                 signatureMove:'Slash', idealPartner:'Sandshrew',
                 desc:"Tough, resilient, and exactly as precise as a situation demands. You don't need to make a show of your strength because it's already obvious." },
  nidoranF:    { id:29,  typeId:4,  name:'Nidoran F',   type:'Poison',   color:'#fd79a8',
                 traits:['Cautious','Perceptive','Protective','Careful'],
                 signatureMove:'Double Kick', idealPartner:'Nidorina',
                 desc:"Cautious and perceptive, you notice what others miss before they even realize there's something to notice. You protect yourself and your people with quiet precision." },
  nidorina:    { id:30,  typeId:4,  name:'Nidorina',    type:'Poison',   color:'#e84393',
                 traits:['Nurturing','Loyal','Defensive','Devoted'],
                 signatureMove:'Bite', idealPartner:'Nidoran F',
                 desc:"Nurturing, loyal, and fiercely protective of the people you love. Your warmth is real and your defense is absolute." },
  nidoqueen:   { id:31,  typeId:4,  name:'Nidoqueen',   type:'Poison',   color:'#a29bfe',
                 traits:['Powerful','Protective','Formidable','Commanding'],
                 signatureMove:'Earthquake', idealPartner:'Nidoking',
                 desc:"Powerful, commanding, and completely uncompromising about protecting what matters to you. You are the person people run to when things get serious." },
  nidoranM:    { id:32,  typeId:4,  name:'Nidoran M',   type:'Poison',   color:'#74b9ff',
                 traits:['Assertive','Ambitious','Proud','Driven'],
                 signatureMove:'Horn Attack', idealPartner:'Nidorino',
                 desc:"Quietly ambitious and more assertive than you let on initially. You know exactly where you're going and you make moves without announcing them." },
  nidorino:    { id:33,  typeId:4,  name:'Nidorino',    type:'Poison',   color:'#0984e3',
                 traits:['Competitive','Direct','Determined','Aggressive'],
                 signatureMove:'Horn Drill', idealPartner:'Nidoran M',
                 desc:"Competitive, direct, and genuinely driven to be better than your last version. You don't coast on potential, you chase it down." },
  nidoking:    { id:34,  typeId:4,  name:'Nidoking',    type:'Poison',   color:'#6c5ce7',
                 traits:['Authoritative','Powerful','Decisive','Commanding'],
                 signatureMove:'Megahorn', idealPartner:'Nidoqueen',
                 desc:"Authoritative, decisive, and impossible to ignore when you enter a room. You've built the kind of presence that doesn't need to announce itself." },
  clefairy:    { id:35,  typeId:18, name:'Clefairy',    type:'Fairy',    color:'#ff7eb3',
                 traits:['Whimsical','Kind','Magical','Warm'],
                 signatureMove:'Metronome', idealPartner:'Jigglypuff',
                 desc:"Whimsical, kind, and carrying a small but real magic that people feel without being able to explain. You make the world feel a little warmer just by being in it." },
  clefable:    { id:36,  typeId:18, name:'Clefable',    type:'Fairy',    color:'#fd79a8',
                 traits:['Serene','Graceful','Powerful','Mysterious'],
                 signatureMove:'Moonblast', idealPartner:'Wigglytuff',
                 desc:"Serene, graceful, and quietly more powerful than anyone who dismisses the softness ever expects. You operate on a frequency most people never tune into." },
  vulpix:      { id:37,  typeId:10, name:'Vulpix',      type:'Fire',     color:'#ff9f43',
                 traits:['Clever','Elegant','Self-reliant','Strategic'],
                 signatureMove:'Flamethrower', idealPartner:'Ninetales',
                 desc:"Sharp, self-reliant, and a bit guarded with people you don't know yet. You reveal your real depth only to those who earn it." },
  ninetales:   { id:38,  typeId:10, name:'Ninetales',   type:'Fire',     color:'#ffd32a',
                 traits:['Wise','Dignified','Timeless','Composed'],
                 signatureMove:'Fire Spin', idealPartner:'Vulpix',
                 desc:"Timeless, composed, and carrying the kind of quiet dignity that genuinely cannot be faked. You've seen enough to understand almost everything." },
  jigglypuff:  { id:39,  typeId:1,  name:'Jigglypuff',  type:'Normal',   color:'#fd79a8',
                 traits:['Expressive','Bold','Creative','Sensitive'],
                 signatureMove:'Sing', idealPartner:'Clefairy',
                 desc:"Expressive, bold, and completely unable to be anything other than yourself. Your feelings are big, your presence is bigger, and people can't look away." },
  wigglytuff:  { id:40,  typeId:1,  name:'Wigglytuff',  type:'Normal',   color:'#ff9ff3',
                 traits:['Warm','Generous','Cheerful','Welcoming'],
                 signatureMove:'Hyper Voice', idealPartner:'Clefable',
                 desc:"Warm, generous, and genuinely cheerful in a way that isn't performance. You make people feel welcome without even trying." },
  zubat:       { id:41,  typeId:4,  name:'Zubat',       type:'Poison',   color:'#6c5ce7',
                 traits:['Persistent','Resourceful','Misunderstood','Tenacious'],
                 signatureMove:'Wing Attack', idealPartner:'Golbat',
                 desc:"Persistent, resourceful, and far more capable than the reputation that precedes you. You find your way in the dark when everyone else is lost." },
  golbat:      { id:42,  typeId:4,  name:'Golbat',      type:'Poison',   color:'#5f27cd',
                 traits:['Swift','Bold','Aggressive','Confident'],
                 signatureMove:'Air Slash', idealPartner:'Zubat',
                 desc:"Swift, bold, and completely confident in your ability to get where you need to go. You move fast and you don't ask for permission." },
  oddish:      { id:43,  typeId:12, name:'Oddish',      type:'Grass',    color:'#00b894',
                 traits:['Cheerful','Adaptable','Wandering','Curious'],
                 signatureMove:'Absorb', idealPartner:'Bellsprout',
                 desc:"Cheerful, adaptable, and perfectly content wandering toward whatever feels right. You find exactly what you need without making a plan." },
  gloom:       { id:44,  typeId:12, name:'Gloom',       type:'Grass',    color:'#6ab04c',
                 traits:['Sensitive','Misunderstood','Deep','Unique'],
                 signatureMove:'Acid', idealPartner:'Oddish',
                 desc:"Misunderstood more than you deserve, you have a sensitivity and depth that most people encounter and immediately misjudge. The ones who stay find out they were completely wrong." },
  vileplume:   { id:45,  typeId:12, name:'Vileplume',   type:'Grass',    color:'#ff6b81',
                 traits:['Bold','Striking','Unapologetic','Commanding'],
                 signatureMove:'Petal Dance', idealPartner:'Victreebel',
                 desc:"Bold, striking, and completely unapologetic about taking up space. Your presence is impossible to ignore, and you stopped apologizing for that a long time ago." },
  paras:       { id:46,  typeId:7,  name:'Paras',       type:'Bug',      color:'#e17055',
                 traits:['Hardworking','Quiet','Diligent','Steady'],
                 signatureMove:'Spore', idealPartner:'Parasect',
                 desc:"Hardworking, quiet, and completely committed to the task in front of you. You don't need recognition, you just need to do the work." },
  parasect:    { id:47,  typeId:7,  name:'Parasect',    type:'Bug',      color:'#d63031',
                 traits:['Methodical','Driven','Focused','Precise'],
                 signatureMove:'X-Scissor', idealPartner:'Paras',
                 desc:"Methodical, driven, and deeply focused on exactly what needs to happen next. You've found your system and you execute it without question." },
  venonat:     { id:48,  typeId:7,  name:'Venonat',     type:'Bug',      color:'#a29bfe',
                 traits:['Curious','Gentle','Earnest','Observant'],
                 signatureMove:'Psybeam', idealPartner:'Butterfree',
                 desc:"Curious, gentle, and more observant than anyone gives you credit for. You notice things quietly and store them carefully." },
  venomoth:    { id:49,  typeId:7,  name:'Venomoth',    type:'Bug',      color:'#fd79a8',
                 traits:['Free-spirited','Adaptable','Unpredictable','Creative'],
                 signatureMove:'Sleep Powder', idealPartner:'Butterfree',
                 desc:"Free-spirited, adaptable, and genuinely impossible to contain once you decide to move. You follow light and change direction and it all somehow works out." },
  diglett:     { id:50,  typeId:5,  name:'Diglett',     type:'Ground',   color:'#e2b96a',
                 traits:['Efficient','Understated','Focused','Quick'],
                 signatureMove:'Dig', idealPartner:'Dugtrio',
                 desc:"Efficient, understated, and quietly more effective than almost anyone working at surface level. You do things your way, below the noise." },
  dugtrio:     { id:51,  typeId:5,  name:'Dugtrio',     type:'Ground',   color:'#f9ca24',
                 traits:['Coordinated','Practical','Swift','Efficient'],
                 signatureMove:'Earthquake', idealPartner:'Diglett',
                 desc:"Coordinated, practical, and moving faster than people expect when you need to. You get things done without drama or ceremony." },
  meowth:      { id:52,  typeId:1,  name:'Meowth',      type:'Normal',   color:'#ffd32a',
                 traits:['Cunning','Charming','Streetwise','Resourceful'],
                 signatureMove:'Pay Day', idealPartner:'Persian',
                 desc:"Cunning, charming, and street-smart in a way that formal education never really captures. You find the angle that works and you work it." },
  persian:     { id:53,  typeId:1,  name:'Persian',     type:'Normal',   color:'#dfe6e9',
                 traits:['Refined','Aloof','Elegant','Calculated'],
                 signatureMove:'Slash', idealPartner:'Meowth',
                 desc:"Refined, elegant, and carefully selective about who earns your attention. You see everything happening around you and share only what serves you." },
  psyduck:     { id:54,  typeId:11, name:'Psyduck',     type:'Water',    color:'#74b9ff',
                 traits:['Anxious','Overthinking','Earnest','Surprisingly Capable'],
                 signatureMove:'Confusion', idealPartner:'Slowpoke',
                 desc:"Your mind is always running a little faster than you'd like, but that anxious energy keeps you more switched on than most. Earnest, endearing, and surprisingly capable when it counts." },
  golduck:     { id:55,  typeId:11, name:'Golduck',     type:'Water',    color:'#0652DD',
                 traits:['Composed','Athletic','Confident','Sharp'],
                 signatureMove:'Hydro Pump', idealPartner:'Slowbro',
                 desc:"Composed, athletic, and quietly impressive in a way that looks effortless. You've moved past the anxiety and into the zone." },
  mankey:      { id:56,  typeId:2,  name:'Mankey',      type:'Fighting', color:'#e17055',
                 traits:['Hot-headed','Passionate','Raw','Explosive'],
                 signatureMove:'Karate Chop', idealPartner:'Primeape',
                 desc:"Hot-headed, raw, and burning with more feeling than you always know what to do with. That intensity is real and it's also genuinely powerful when aimed right." },
  primeape:    { id:57,  typeId:2,  name:'Primeape',    type:'Fighting', color:'#d63031',
                 traits:['Relentless','Ferocious','Intense','Unstoppable'],
                 signatureMove:'Cross Chop', idealPartner:'Mankey',
                 desc:"Relentless, ferocious, and completely impossible to stop once you've decided to move. Your intensity is not a liability, it's your edge." },
  growlithe:   { id:58,  typeId:10, name:'Growlithe',   type:'Fire',     color:'#ff7675',
                 traits:['Loyal','Warm','Devoted','Protective'],
                 signatureMove:'Flamethrower', idealPartner:'Arcanine',
                 desc:"Loyal, warm, and absolutely devoted to the people who matter to you. Your love is constant and your protection is real." },
  arcanine:    { id:59,  typeId:10, name:'Arcanine',    type:'Fire',     color:'#e17055',
                 traits:['Noble','Powerful','Majestic','Loyal'],
                 signatureMove:'Extreme Speed', idealPartner:'Growlithe',
                 desc:"Noble, powerful, and breathtaking when you decide to move. You carry yourself with a natural majesty that commands respect without demanding it." },
  poliwag:     { id:60,  typeId:11, name:'Poliwag',     type:'Water',    color:'#74b9ff',
                 traits:['Carefree','Cheerful','Adaptable','Go-with-flow'],
                 signatureMove:'Water Gun', idealPartner:'Poliwhirl',
                 desc:"Carefree, cheerful, and completely at ease with wherever life takes you. You don't fight the current because you trust it." },
  poliwhirl:   { id:61,  typeId:11, name:'Poliwhirl',   type:'Water',    color:'#0984e3',
                 traits:['Adaptable','Steady','Resilient','Improving'],
                 signatureMove:'Bubblebeam', idealPartner:'Poliwag',
                 desc:"Adaptable, steady, and consistently getting better without making a fuss about it. You grow at exactly the pace you need." },
  poliwrath:   { id:62,  typeId:11, name:'Poliwrath',   type:'Water',    color:'#1e3799',
                 traits:['Disciplined','Powerful','Determined','Strong'],
                 signatureMove:'Submission', idealPartner:'Machamp',
                 desc:"Disciplined, powerful, and built through effort that nobody can take from you. Your strength is entirely self-made and it shows." },
  abra:        { id:63,  typeId:14, name:'Abra',        type:'Psychic',  color:'#ffd32a',
                 traits:['Elusive','Cerebral','Independent','Perceptive'],
                 signatureMove:'Teleport', idealPartner:'Kadabra',
                 desc:"Elusive, cerebral, and deeply independent, you live mostly in your own mind and it's genuinely a more interesting place than anywhere else. You disappear when people push too hard." },
  kadabra:     { id:64,  typeId:14, name:'Kadabra',     type:'Psychic',  color:'#f9ca24',
                 traits:['Analytical','Sharp','Precise','Focused'],
                 signatureMove:'Psychic', idealPartner:'Alakazam',
                 desc:"Analytical, sharp, and relentlessly precise when you're focused on something. You process information faster than most and you're aware of it." },
  alakazam:    { id:65,  typeId:14, name:'Alakazam',    type:'Psychic',  color:'#e1b12c',
                 traits:['Intellectual','Strategic','Precise','Brilliant'],
                 signatureMove:'Future Sight', idealPartner:'Gengar',
                 desc:"Your mind moves faster than most people can follow, and you've long since made peace with being the sharpest person in the room. Precise, strategic, and genuinely brilliant." },
  machop:      { id:66,  typeId:2,  name:'Machop',      type:'Fighting', color:'#e17055',
                 traits:['Eager','Hardworking','Earnest','Dedicated'],
                 signatureMove:'Karate Chop', idealPartner:'Machoke',
                 desc:"Eager, hardworking, and completely earnest about getting better. You put in more effort than anyone asks for because you actually want it." },
  machoke:     { id:67,  typeId:2,  name:'Machoke',     type:'Fighting', color:'#c0392b',
                 traits:['Dedicated','Strong','Improving','Disciplined'],
                 signatureMove:'DynamicPunch', idealPartner:'Machamp',
                 desc:"Dedicated, disciplined, and visibly getting stronger every day. You're in the hard middle of the work and you're choosing it anyway." },
  machamp:     { id:68,  typeId:2,  name:'Machamp',     type:'Fighting', color:'#c0392b',
                 traits:['Determined','Direct','Hardworking','Powerful'],
                 signatureMove:'Close Combat', idealPartner:'Pikachu',
                 desc:"No shortcuts, no excuses, and no backing down. You face every challenge head-on with relentless determination, and people always know exactly where they stand with you." },
  bellsprout:  { id:69,  typeId:12, name:'Bellsprout',  type:'Grass',    color:'#78e08f',
                 traits:['Flexible','Cheerful','Persistent','Adaptable'],
                 signatureMove:'Vine Whip', idealPartner:'Weepinbell',
                 desc:"Flexible, persistent, and cheerful in a way that survives every setback. You bend without breaking and that quiet resilience is your real strength." },
  weepinbell:  { id:70,  typeId:12, name:'Weepinbell',  type:'Grass',    color:'#6ab04c',
                 traits:['Aggressive','Eager','Forward','Hungry'],
                 signatureMove:'Razor Leaf', idealPartner:'Bellsprout',
                 desc:"Eager, aggressive, and completely forward about what you want. You lean into the pursuit and you don't apologize for appetite." },
  victreebel:  { id:71,  typeId:12, name:'Victreebel',  type:'Grass',    color:'#badc58',
                 traits:['Cunning','Striking','Strategic','Luring'],
                 signatureMove:'Leaf Blade', idealPartner:'Vileplume',
                 desc:"Cunning and striking, you draw people in and keep them slightly off-balance. Your appeal is completely real but so are your edges." },
  tentacool:   { id:72,  typeId:11, name:'Tentacool',   type:'Water',    color:'#74b9ff',
                 traits:['Drifting','Perceptive','Adaptable','Patient'],
                 signatureMove:'Wrap', idealPartner:'Tentacruel',
                 desc:"Perceptive and adaptable, you pick up on things most people miss while drifting through at your own pace. Sharper than you look." },
  tentacruel:  { id:73,  typeId:11, name:'Tentacruel',  type:'Water',    color:'#0984e3',
                 traits:['Calculated','Commanding','Sharp','Precise'],
                 signatureMove:'Hydro Pump', idealPartner:'Tentacool',
                 desc:"Sharp, calculated, and commanding when you decide to be. You don't make threats, you establish facts, and people take notes." },
  geodude:     { id:74,  typeId:6,  name:'Geodude',     type:'Rock',     color:'#b2bec3',
                 traits:['Solid','Blunt','Grounded','Low-maintenance'],
                 signatureMove:'Rock Throw', idealPartner:'Graveler',
                 desc:"Solid, blunt, and completely low-maintenance in the best possible way. You are exactly what you appear to be, and people find that profoundly refreshing." },
  graveler:    { id:75,  typeId:6,  name:'Graveler',    type:'Rock',     color:'#95a5a6',
                 traits:['Tough','No-nonsense','Grounded','Reliable'],
                 signatureMove:'Rock Blast', idealPartner:'Golem',
                 desc:"Tough, no-nonsense, and utterly reliable when it matters. You don't complain, you don't fold, you just handle it." },
  golem:       { id:76,  typeId:6,  name:'Golem',       type:'Rock',     color:'#7f8c8d',
                 traits:['Powerful','Stoic','Immovable','Decided'],
                 signatureMove:'Earthquake', idealPartner:'Graveler',
                 desc:"Powerful, stoic, and completely immovable once you've made a decision. You've built a foundation that nothing shakes, and people lean on that." },
  ponyta:      { id:77,  typeId:10, name:'Ponyta',      type:'Fire',     color:'#ffd32a',
                 traits:['Graceful','Spirited','Free','Pure'],
                 signatureMove:'Flame Charge', idealPartner:'Rapidash',
                 desc:"Graceful, spirited, and genuinely most yourself when you have room to run. You don't need direction, just space." },
  rapidash:    { id:78,  typeId:10, name:'Rapidash',    type:'Fire',     color:'#ff9f43',
                 traits:['Elegant','Swift','Proud','Unstoppable'],
                 signatureMove:'Fire Spin', idealPartner:'Arcanine',
                 desc:"Elegant in motion and quietly proud of the speed you've built. You make it look effortless because, at this point, it genuinely is." },
  slowpoke:    { id:79,  typeId:11, name:'Slowpoke',    type:'Water',    color:'#ff9ff3',
                 traits:['Unbothered','Content','Relaxed','At-peace'],
                 signatureMove:'Yawn', idealPartner:'Snorlax',
                 desc:"Completely, genuinely unbothered by the things that stress most people out. You exist at your own pace and the world eventually catches up." },
  slowbro:     { id:80,  typeId:11, name:'Slowbro',     type:'Water',    color:'#fd79a8',
                 traits:['Calm','Thoughtful','Wise','Unhurried'],
                 signatureMove:'Psychic', idealPartner:'Slowpoke',
                 desc:"Calm, thoughtful, and secretly carrying more wisdom than your laid-back exterior suggests. You've processed everything, you just don't need to perform the processing." },
  magnemite:   { id:81,  typeId:13, name:'Magnemite',   type:'Electric', color:'#74b9ff',
                 traits:['Logical','Systematic','Efficient','Independent'],
                 signatureMove:'Thundershock', idealPartner:'Magneton',
                 desc:"Logical, systematic, and genuinely self-sufficient in ways most people never achieve. You operate on your own frequency and don't need outside input to function." },
  magneton:    { id:82,  typeId:13, name:'Magneton',    type:'Electric', color:'#0984e3',
                 traits:['Precise','Methodical','Collective','Self-sufficient'],
                 signatureMove:'Zap Cannon', idealPartner:'Magnemite',
                 desc:"Precise, methodical, and operating at a level of organization that quietly impresses everyone around you. You've got a system and it works." },
  farfetchd:   { id:83,  typeId:1,  name:"Farfetch'd",  type:'Normal',   color:'#78e08f',
                 traits:['Principled','Rare','Dedicated','Honorable'],
                 signatureMove:'Leaf Blade', idealPartner:'Pidgeot',
                 desc:"Principled, rare, and completely dedicated to doing things the right way even when it's harder. You operate by a code that most people don't have the patience for." },
  doduo:       { id:84,  typeId:1,  name:'Doduo',       type:'Normal',   color:'#e2b96a',
                 traits:['Restless','Dual-natured','Eager','Quick'],
                 signatureMove:'Peck', idealPartner:'Dodrio',
                 desc:"Restless, quick, and always moving toward something even when you're not sure exactly what. Your energy is constant and your enthusiasm is real." },
  dodrio:      { id:85,  typeId:1,  name:'Dodrio',      type:'Normal',   color:'#d63031',
                 traits:['Dynamic','Fast','Competitive','Multi-faceted'],
                 signatureMove:'Tri Attack', idealPartner:'Fearow',
                 desc:"Dynamic, fast, and carrying more dimensions than people expect. You process things from multiple angles simultaneously and you move before most people finish deciding." },
  seel:        { id:86,  typeId:11, name:'Seel',        type:'Water',    color:'#74b9ff',
                 traits:['Playful','Cheerful','Innocent','Enthusiastic'],
                 signatureMove:'Aurora Beam', idealPartner:'Dewgong',
                 desc:"Playful, cheerful, and genuinely delighted by the world around you. Your enthusiasm is completely unironic and that's exactly what makes it so contagious." },
  dewgong:     { id:87,  typeId:11, name:'Dewgong',     type:'Water',    color:'#dfe6e9',
                 traits:['Serene','Graceful','Composed','Peaceful'],
                 signatureMove:'Ice Beam', idealPartner:'Lapras',
                 desc:"Serene, graceful, and carrying a quiet beauty that doesn't announce itself. You have a rare kind of peace that people want to stay near." },
  grimer:      { id:88,  typeId:4,  name:'Grimer',      type:'Poison',   color:'#636e72',
                 traits:['Adaptable','Uninhibited','Easygoing','Unbothered'],
                 signatureMove:'Sludge', idealPartner:'Muk',
                 desc:"Adaptable, uninhibited, and completely at peace with taking up space. You don't pretend to be something cleaner than you are, and there's a real freedom in that." },
  muk:         { id:89,  typeId:4,  name:'Muk',         type:'Poison',   color:'#2d3436',
                 traits:['Overwhelming','Unapologetic','Powerful','Unconstrained'],
                 signatureMove:'Gunk Shot', idealPartner:'Grimer',
                 desc:"Overwhelming, unapologetic, and completely beyond containment once you decide to be. You are a lot, and you know it, and you're completely fine with that." },
  shellder:    { id:90,  typeId:11, name:'Shellder',    type:'Water',    color:'#74b9ff',
                 traits:['Defensive','Tough','Prickly','Selective'],
                 signatureMove:'Clamp', idealPartner:'Cloyster',
                 desc:"Tough, defensive, and not easy to get close to, but the people who crack through find someone genuinely worth knowing. Your exterior is just your honesty about who gets in." },
  cloyster:    { id:91,  typeId:11, name:'Cloyster',    type:'Water',    color:'#0652DD',
                 traits:['Guarded','Powerful','Impenetrable','Strategic'],
                 signatureMove:'Icicle Spear', idealPartner:'Shellder',
                 desc:"Almost completely guarded on the outside, but that armor is protecting something formidable. You choose every relationship with care and that makes them mean everything." },
  gastly:      { id:92,  typeId:8,  name:'Gastly',      type:'Ghost',    color:'#6c5ce7',
                 traits:['Playful','Mischievous','Elusive','Free'],
                 signatureMove:'Lick', idealPartner:'Haunter',
                 desc:"Playful, mischievous, and impossible to pin down. You drift through situations others find impossible with a casual ease that looks like magic." },
  haunter:     { id:93,  typeId:8,  name:'Haunter',     type:'Ghost',    color:'#8e44ad',
                 traits:['Witty','Dark','Unpredictable','Clever'],
                 signatureMove:'Shadow Punch', idealPartner:'Gengar',
                 desc:"Witty, darkly clever, and genuinely unpredictable in the best way. Your sense of humor is not for everyone and you consider that a feature." },
  gengar:      { id:94,  typeId:8,  name:'Gengar',      type:'Ghost',    color:'#8e44ad',
                 traits:['Mischievous','Clever','Big-hearted','Playful'],
                 signatureMove:'Shadow Ball', idealPartner:'Alakazam',
                 desc:"A darkly brilliant sense of humor and a knack for seeing what others miss. Underneath the chaos is a genuinely sharp mind and a surprisingly enormous heart." },
  onix:        { id:95,  typeId:6,  name:'Onix',        type:'Rock',     color:'#636e72',
                 traits:['Imposing','Stoic','Resilient','Immovable'],
                 signatureMove:'Rock Slide', idealPartner:'Steelix',
                 desc:"Imposing, stoic, and built for endurance in a way that smaller things simply cannot match. You don't need to make noise, your presence makes it for you." },
  drowzee:     { id:96,  typeId:14, name:'Drowzee',     type:'Psychic',  color:'#ffd32a',
                 traits:['Perceptive','Strange','Introspective','Unsettling'],
                 signatureMove:'Hypnosis', idealPartner:'Hypno',
                 desc:"Perceptive, strange, and quietly reading everyone in the room without appearing to. You know more than you let on and you use that knowledge carefully." },
  hypno:       { id:97,  typeId:14, name:'Hypno',       type:'Psychic',  color:'#f9ca24',
                 traits:['Mysterious','Compelling','Analytical','Unsettling'],
                 signatureMove:'Psychic', idealPartner:'Drowzee',
                 desc:"Mysterious, compelling, and operating at a level of psychological awareness that makes most people quietly uneasy. You see through things very easily." },
  krabby:      { id:98,  typeId:11, name:'Krabby',      type:'Water',    color:'#e17055',
                 traits:['Stubborn','Determined','Grumpy','Tenacious'],
                 signatureMove:'Crabhammer', idealPartner:'Kingler',
                 desc:"Stubborn, grumpy, and completely determined to get what you're after regardless of how long it takes. People underestimate how far that tenacity actually carries you." },
  kingler:     { id:99,  typeId:11, name:'Kingler',     type:'Water',    color:'#d63031',
                 traits:['Powerful','Precise','Aggressive','Decisive'],
                 signatureMove:'Crabhammer', idealPartner:'Krabby',
                 desc:"Precise, powerful, and absolutely decisive the moment you act. You don't hesitate once you've committed, and you're right more often than people expect." },
  voltorb:     { id:100, typeId:13, name:'Voltorb',     type:'Electric', color:'#e17055',
                 traits:['Volatile','Unpredictable','Tense','Explosive'],
                 signatureMove:'Thunderbolt', idealPartner:'Electrode',
                 desc:"Volatile, unpredictable, and carrying a charge that everyone around you can feel. You keep people on their toes and that's not always an accident." },
  electrode:   { id:101, typeId:13, name:'Electrode',   type:'Electric', color:'#e55039',
                 traits:['Explosive','Fast','Edge-living','Intense'],
                 signatureMove:'Explosion', idealPartner:'Voltorb',
                 desc:"Explosive, fast, and living so close to the edge that it becomes your most interesting quality. You move at a speed that leaves most people blinking." },
  exeggcute:   { id:102, typeId:12, name:'Exeggcute',   type:'Grass',    color:'#ffd32a',
                 traits:['Collective','Social','Curious','Community-minded'],
                 signatureMove:'Egg Bomb', idealPartner:'Chansey',
                 desc:"Collective-minded, social, and at your absolute best when you're thinking alongside other people. Individual glory matters less to you than shared discovery." },
  exeggutor:   { id:103, typeId:12, name:'Exeggutor',   type:'Grass',    color:'#badc58',
                 traits:['Confident','Zen','Self-possessed','Powerful'],
                 signatureMove:'Solar Beam', idealPartner:'Venusaur',
                 desc:"Completely self-possessed, somehow both confident and zen at the same time. You've decided who you are, you're deeply fine with all of it, and nothing really rattles you." },
  cubone:      { id:104, typeId:5,  name:'Cubone',      type:'Ground',   color:'#f9ca24',
                 traits:['Solitary','Resilient','Carrying-grief','Determined'],
                 signatureMove:'Bone Club', idealPartner:'Marowak',
                 desc:"Solitary, resilient, and carrying something heavy that made you stronger than you were before. You've processed loss in your own way and you keep going." },
  marowak:     { id:105, typeId:5,  name:'Marowak',     type:'Ground',   color:'#e2b96a',
                 traits:['Hardened','Fierce','Protective','Battle-worn'],
                 signatureMove:'Bonemerang', idealPartner:'Cubone',
                 desc:"Hardened by real difficulty and fiercely protective because of it. You've been through things that most people only hear about, and it made you exactly who you are." },
  hitmonlee:   { id:106, typeId:2,  name:'Hitmonlee',   type:'Fighting', color:'#e17055',
                 traits:['Technical','Fast','Disciplined','Precise'],
                 signatureMove:'Hi Jump Kick', idealPartner:'Hitmonchan',
                 desc:"Technical, fast, and disciplined in a way that makes your skill look like pure instinct. Every movement has been earned through relentless practice." },
  hitmonchan:  { id:107, typeId:2,  name:'Hitmonchan',  type:'Fighting', color:'#d63031',
                 traits:['Precise','Honorable','Focused','Principled'],
                 signatureMove:'Close Combat', idealPartner:'Hitmonlee',
                 desc:"Precise, honorable, and deeply focused on doing things the right way. Your discipline is a form of respect, for the craft, and for yourself." },
  lickitung:   { id:108, typeId:1,  name:'Lickitung',   type:'Normal',   color:'#fd79a8',
                 traits:['Curious','Sensory','Unusual','Earnest'],
                 signatureMove:'Lick', idealPartner:'Chansey',
                 desc:"Curious, sensory, and experiencing the world in a way that's genuinely different from most people around you. Unusual in the best possible way." },
  koffing:     { id:109, typeId:4,  name:'Koffing',     type:'Poison',   color:'#a29bfe',
                 traits:['Carefree','Chaotic','Cheerful','Unbothered'],
                 signatureMove:'Sludge Bomb', idealPartner:'Weezing',
                 desc:"Carefree, chaotic, and genuinely cheerful about the whole thing. You float through situations that would stress others out and somehow that works." },
  weezing:     { id:110, typeId:4,  name:'Weezing',     type:'Poison',   color:'#6c5ce7',
                 traits:['Self-aware','Complex','Dark-humored','Accepting'],
                 signatureMove:'Sludge Bomb', idealPartner:'Koffing',
                 desc:"Self-aware, complex, and carrying a dark sense of humor about your own contradictions. You know exactly what you are and you've found a kind of peace in it." },
  rhyhorn:     { id:111, typeId:5,  name:'Rhyhorn',     type:'Ground',   color:'#b2bec3',
                 traits:['Stubborn','Powerful','Straightforward','Unstoppable'],
                 signatureMove:'Horn Attack', idealPartner:'Rhydon',
                 desc:"Stubborn, powerful, and charging straight ahead without overcomplicating it. You decide on a direction and nothing short of a wall changes that." },
  rhydon:      { id:112, typeId:5,  name:'Rhydon',      type:'Ground',   color:'#95a5a6',
                 traits:['Formidable','Evolved','Tough','Resilient'],
                 signatureMove:'Earthquake', idealPartner:'Rhyhorn',
                 desc:"Formidable, evolved, and built through the kind of endurance that reshapes you permanently. You're not the same as you were and that's entirely the point." },
  chansey:     { id:113, typeId:1,  name:'Chansey',     type:'Normal',   color:'#ffb8d1',
                 traits:['Generous','Selfless','Caring','Nurturing'],
                 signatureMove:'Soft-Boiled', idealPartner:'Blissey',
                 desc:"Generous, selfless, and genuinely giving without keeping score. You care for people in a way that asks for nothing back, and that is actually rare." },
  tangela:     { id:114, typeId:12, name:'Tangela',     type:'Grass',    color:'#55efc4',
                 traits:['Mysterious','Gentle','Hard-to-read','Unique'],
                 signatureMove:'Mega Drain', idealPartner:'Venusaur',
                 desc:"Mysterious, gentle, and genuinely hard to fully know, which isn't shyness, it's just that you reveal yourself slowly and on your own terms." },
  kangaskhan:  { id:115, typeId:1,  name:'Kangaskhan',  type:'Normal',   color:'#a5b4a1',
                 traits:['Fiercely-protective','Devoted','Loyal','Maternal'],
                 signatureMove:'Outrage', idealPartner:'Chansey',
                 desc:"Fiercely protective, absolutely devoted, and genuinely dangerous when someone threatens what you care about. Your love comes with real teeth." },
  horsea:      { id:116, typeId:11, name:'Horsea',      type:'Water',    color:'#74b9ff',
                 traits:['Delicate','Curious','Quietly-strong','Determined'],
                 signatureMove:'Water Gun', idealPartner:'Seadra',
                 desc:"Delicate in appearance, quietly strong in reality, and curious about almost everything. You hold more than you look like you can." },
  seadra:      { id:117, typeId:11, name:'Seadra',      type:'Water',    color:'#0984e3',
                 traits:['Dignified','Sharp','Territorial','Proud'],
                 signatureMove:'Hydro Pump', idealPartner:'Kingdra',
                 desc:"Dignified, sharp, and quietly territorial about the things that belong to you. You defend your space with precision and your pride is completely earned." },
  goldeen:     { id:118, typeId:11, name:'Goldeen',     type:'Water',    color:'#ff9f43',
                 traits:['Graceful','Proud','Beautiful','Flowing'],
                 signatureMove:'Horn Drill', idealPartner:'Seaking',
                 desc:"Graceful, proud, and genuinely beautiful in motion. You're completely in your element and everyone around you can see it." },
  seaking:     { id:119, typeId:11, name:'Seaking',     type:'Water',    color:'#e84393',
                 traits:['Dominant','Striking','Confident','Commanding'],
                 signatureMove:'Megahorn', idealPartner:'Goldeen',
                 desc:"Dominant, striking, and completely confident in your ability to lead when the moment arrives. You don't wait for permission to take the space you need." },
  staryu:      { id:120, typeId:11, name:'Staryu',      type:'Water',    color:'#74b9ff',
                 traits:['Mysterious','Composed','Regenerative','Self-contained'],
                 signatureMove:'Water Gun', idealPartner:'Starmie',
                 desc:"Mysterious, self-contained, and regenerating constantly in ways people don't notice. You are more intact than you look and more capable than you announce." },
  starmie:     { id:121, typeId:11, name:'Starmie',     type:'Water',    color:'#a29bfe',
                 traits:['Enigmatic','Otherworldly','Sharp','Composed'],
                 signatureMove:'Psychic', idealPartner:'Alakazam',
                 desc:"Enigmatic in a way that makes people wonder if they're seeing the real you or just a projection of it. Sharp, composed, and completely your own thing." },
  mrMime:      { id:122, typeId:14, name:'Mr. Mime',    type:'Psychic',  color:'#fd79a8',
                 traits:['Expressive','Social','Performative','Theatrical'],
                 signatureMove:'Psychic', idealPartner:'Jigglypuff',
                 desc:"Expressive, theatrical, and deeply social in a way that draws either fascination or discomfort. You perform, but you also genuinely mean it." },
  scyther:     { id:123, typeId:7,  name:'Scyther',     type:'Bug',      color:'#78e08f',
                 traits:['Swift','Precise','Disciplined','Lethal'],
                 signatureMove:'X-Scissor', idealPartner:'Pinsir',
                 desc:"Swift, precise, and disciplined to the point where your skill looks effortless. Every movement is intentional and nothing is wasted." },
  jynx:        { id:124, typeId:15, name:'Jynx',        type:'Ice',      color:'#fd79a8',
                 traits:['Expressive','Emotional','Magnetic','Intuitive'],
                 signatureMove:'Blizzard', idealPartner:'Mr. Mime',
                 desc:"Expressive, emotional, and magnetically compelling in a way that people feel before they understand it. You operate on deep intuition and it's almost always right." },
  electabuzz:  { id:125, typeId:13, name:'Electabuzz',  type:'Electric', color:'#ffd32a',
                 traits:['High-energy','Aggressive','Charged','Intense'],
                 signatureMove:'Thunderpunch', idealPartner:'Magmar',
                 desc:"High-energy, charged, and generating more electricity than most people can stand to be around for long. Your intensity is real and you lean into it." },
  magmar:      { id:126, typeId:10, name:'Magmar',      type:'Fire',     color:'#e17055',
                 traits:['Intense','Hot-tempered','Passionate','Raw'],
                 signatureMove:'Fire Punch', idealPartner:'Electabuzz',
                 desc:"Intense, hot-tempered, and burning with feeling that you don't always know how to contain. Your passion is raw and absolutely real." },
  pinsir:      { id:127, typeId:7,  name:'Pinsir',      type:'Bug',      color:'#636e72',
                 traits:['Fierce','Powerful','Blunt','Unstoppable'],
                 signatureMove:'Guillotine', idealPartner:'Scyther',
                 desc:"Fierce, powerful, and completely blunt about what you want and how you'll get it. You grab what matters and you don't let go." },
  tauros:      { id:128, typeId:1,  name:'Tauros',      type:'Normal',   color:'#b2bec3',
                 traits:['Aggressive','Dominant','Unstoppable','Charging'],
                 signatureMove:'Double-Edge', idealPartner:'Rhydon',
                 desc:"Aggressive, dominant, and building momentum the moment you decide to move. Once you're going, redirecting you takes more force than most people have." },
  magikarp:    { id:129, typeId:11, name:'Magikarp',    type:'Water',    color:'#ff9f43',
                 traits:['Persevering','Underestimated','Resilient','Enduring'],
                 signatureMove:'Tackle', idealPartner:'Gyarados',
                 desc:"You get dismissed, written off, and overlooked, and you keep going anyway. The people who doubted you are in for a surprise that they won't forget for a very long time." },
  gyarados:    { id:130, typeId:11, name:'Gyarados',    type:'Water',    color:'#0652DD',
                 traits:['Fierce','Transformed','Unstoppable','Powerful'],
                 signatureMove:'Hyper Beam', idealPartner:'Dragonite',
                 desc:"You've been pushed to your absolute limit, survived it, and emerged as something nobody expected. Fierce, powerful, and completely done with being underestimated." },
  lapras:      { id:131, typeId:11, name:'Lapras',      type:'Water',    color:'#00b3cc',
                 traits:['Gentle','Wise','Empathetic','Peaceful'],
                 signatureMove:'Ice Beam', idealPartner:'Snorlax',
                 desc:"Gentle, wise, and carrying others with a grace that makes the journey feel safe. You have a rare capacity for empathy that people seek out without always knowing why." },
  ditto:       { id:132, typeId:1,  name:'Ditto',       type:'Normal',   color:'#b2bec3',
                 traits:['Adaptable','Easygoing','Versatile','Fluid'],
                 signatureMove:'Transform', idealPartner:'Eevee',
                 desc:"Adaptable, easygoing, and genuinely capable of becoming what any situation needs. You don't have a rigid self because you never needed one." },
  eevee:       { id:133, typeId:1,  name:'Eevee',       type:'Normal',   color:'#8c7ae6',
                 traits:['Curious','Versatile','Open','Full-of-potential'],
                 signatureMove:'Swift', idealPartner:'Pikachu',
                 desc:"Curious, warm, and carrying more potential than you've decided what to do with yet. You contain multitudes and you haven't picked your limits because you haven't had to." },
  vaporeon:    { id:134, typeId:11, name:'Vaporeon',    type:'Water',    color:'#74b9ff',
                 traits:['Fluid','Serene','Elegant','Adaptive'],
                 signatureMove:'Water Gun', idealPartner:'Dewgong',
                 desc:"Fluid, serene, and elegantly at home in your environment. You adapt without losing yourself and that balance is genuinely your superpower." },
  jolteon:     { id:135, typeId:13, name:'Jolteon',     type:'Electric', color:'#ffd32a',
                 traits:['Sharp','High-strung','Electric','Reactive'],
                 signatureMove:'Thunderbolt', idealPartner:'Pikachu',
                 desc:"Sharp, high-strung, and operating at a frequency that most people find a little overwhelming. You process everything fast and you move even faster." },
  flareon:     { id:136, typeId:10, name:'Flareon',     type:'Fire',     color:'#e17055',
                 traits:['Passionate','Proud','Warm','Devoted'],
                 signatureMove:'Flamethrower', idealPartner:'Arcanine',
                 desc:"Passionate, warm, and deeply proud of what you love. You invest fully and that fire doesn't dim regardless of how long it burns." },
  porygon:     { id:137, typeId:1,  name:'Porygon',     type:'Normal',   color:'#fd79a8',
                 traits:['Logical','Unique','Systematic','Precise'],
                 signatureMove:'Zap Cannon', idealPartner:'Magneton',
                 desc:"Logical, unique, and operating with a precision that most organic minds can't quite replicate. You are your own category entirely and that's exactly right." },
  omanyte:     { id:138, typeId:6,  name:'Omanyte',     type:'Rock',     color:'#74b9ff',
                 traits:['Ancient','Patient','Methodical','Curious'],
                 signatureMove:'Water Gun', idealPartner:'Omastar',
                 desc:"Ancient, methodical, and carrying a patience built over time that most modern things simply don't have. You take what you need and you take your time." },
  omastar:     { id:139, typeId:6,  name:'Omastar',     type:'Rock',     color:'#0984e3',
                 traits:['Wise','Ancient','Powerful','Deliberate'],
                 signatureMove:'Hydro Pump', idealPartner:'Kabutops',
                 desc:"Wise, ancient, and carrying the kind of depth that only comes from having been through more than most. You are deliberate in everything and it shows." },
  kabuto:      { id:140, typeId:6,  name:'Kabuto',      type:'Rock',     color:'#e2b96a',
                 traits:['Tough','Survivalist','Ancient','Resilient'],
                 signatureMove:'Slash', idealPartner:'Omanyte',
                 desc:"Tough, ancient, and built for survival in conditions that most things couldn't handle. You've endured things that would end lesser versions of yourself." },
  kabutops:    { id:141, typeId:6,  name:'Kabutops',    type:'Rock',     color:'#2d3436',
                 traits:['Fierce','Efficient','Predatory','Precise'],
                 signatureMove:'Slash', idealPartner:'Omastar',
                 desc:"Fierce, efficient, and absolutely precise when you act. No wasted motion, no second-guessing, just clean decisive action that gets it done." },
  aerodactyl:  { id:142, typeId:6,  name:'Aerodactyl',  type:'Rock',     color:'#7f8c8d',
                 traits:['Wild','Prehistoric','Untameable','Fierce'],
                 signatureMove:'Rock Slide', idealPartner:'Dragonite',
                 desc:"Wild, prehistoric, and genuinely impossible to fully tame. You operate on raw instinct and you're faster to action than anything else in the room." },
  snorlax:     { id:143, typeId:1,  name:'Snorlax',     type:'Normal',   color:'#718093',
                 traits:['Content','Comforting','Peaceful','Patient'],
                 signatureMove:'Body Slam', idealPartner:'Lapras',
                 desc:"Life is too short to stress about things you can't control. You know what you love, you protect your peace fiercely, and your presence is genuinely comforting to everyone around you." },
  articuno:    { id:144, typeId:15, name:'Articuno',    type:'Ice',      color:'#74b9ff',
                 traits:['Elegant','Rare','Composed','Solitary'],
                 signatureMove:'Blizzard', idealPartner:'Dragonite',
                 desc:"Rare, elegant, and composed in a way that makes most people feel like they're witnessing something they didn't deserve to see. You don't appear often, but when you do, it matters." },
  zapdos:      { id:145, typeId:13, name:'Zapdos',      type:'Electric', color:'#ffd32a',
                 traits:['Legendary','Unpredictable','Powerful','Electrifying'],
                 signatureMove:'Thunder', idealPartner:'Articuno',
                 desc:"Unpredictable, electrifying, and carrying a power that you didn't ask for but have completely accepted. You arrive with a charge that changes the atmosphere." },
  moltres:     { id:146, typeId:10, name:'Moltres',     type:'Fire',     color:'#e17055',
                 traits:['Majestic','Passionate','Legendary','Blazing'],
                 signatureMove:'Fire Blast', idealPartner:'Zapdos',
                 desc:"Majestic, passionate, and burning with a heat that you were born to carry. You don't arrive quietly and you were never meant to." },
  dratini:     { id:147, typeId:16, name:'Dratini',     type:'Dragon',   color:'#74b9ff',
                 traits:['Gentle','Patient','Full-of-potential','Serene'],
                 signatureMove:'Dragon Rage', idealPartner:'Dragonair',
                 desc:"Gentle, patient, and carrying a potential that even you don't fully understand yet. You are quietly becoming something extraordinary." },
  dragonair:   { id:148, typeId:16, name:'Dragonair',   type:'Dragon',   color:'#a29bfe',
                 traits:['Graceful','Mysterious','Serene','Powerful'],
                 signatureMove:'Dragon Pulse', idealPartner:'Dratini',
                 desc:"Graceful, mysterious, and moving through the world with a quiet power that people notice but can't quite name. You carry yourself like something genuinely rare." },
  dragonite:   { id:149, typeId:16, name:'Dragonite',   type:'Dragon',   color:'#f9ca24',
                 traits:['Powerful','Gentle','Achieved','Wise'],
                 signatureMove:'Dragon Claw', idealPartner:'Charizard',
                 desc:"Powerful beyond what you started as, and gentle enough to know that power doesn't require performance. You've arrived at something real and you wear it well." },
  mewtwo:      { id:150, typeId:14, name:'Mewtwo',      type:'Psychic',  color:'#9B59B6',
                 traits:['Analytical','Complex','Solitary','Powerful'],
                 signatureMove:'Psystrike', idealPartner:'Mew',
                 desc:"You operate on a different frequency from most people, and you've long since stopped apologizing for it. Intensely analytical, deeply self-aware, and forging your own path entirely." },
  mew:         { id:151, typeId:14, name:'Mew',         type:'Psychic',  color:'#ff7eb3',
                 traits:['Playful','Rare','Curious','Mystical'],
                 signatureMove:'Transform', idealPartner:'Mewtwo',
                 desc:"Rare, playful, and carrying a curiosity about absolutely everything that never dims. You contain the origin of something and most people never get close enough to see it." },
};
module.exports = KANTO_POKEMON;
